/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package com.google.android.gms.base;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int buttonSize = 0x7f040073;
        public static final int circleCrop = 0x7f0400a5;
        public static final int colorScheme = 0x7f0400c4;
        public static final int imageAspectRatio = 0x7f04016d;
        public static final int imageAspectRatioAdjust = 0x7f04016e;
        public static final int scopeUris = 0x7f040253;
    }
    public static final class color {
        private color() {}

        public static final int common_google_signin_btn_text_dark = 0x7f060046;
        public static final int common_google_signin_btn_text_dark_default = 0x7f060047;
        public static final int common_google_signin_btn_text_dark_disabled = 0x7f060048;
        public static final int common_google_signin_btn_text_dark_focused = 0x7f060049;
        public static final int common_google_signin_btn_text_dark_pressed = 0x7f06004a;
        public static final int common_google_signin_btn_text_light = 0x7f06004b;
        public static final int common_google_signin_btn_text_light_default = 0x7f06004c;
        public static final int common_google_signin_btn_text_light_disabled = 0x7f06004d;
        public static final int common_google_signin_btn_text_light_focused = 0x7f06004e;
        public static final int common_google_signin_btn_text_light_pressed = 0x7f06004f;
        public static final int common_google_signin_btn_tint = 0x7f060050;
    }
    public static final class drawable {
        private drawable() {}

        public static final int common_full_open_on_phone = 0x7f08009f;
        public static final int common_google_signin_btn_icon_dark = 0x7f0800a0;
        public static final int common_google_signin_btn_icon_dark_focused = 0x7f0800a1;
        public static final int common_google_signin_btn_icon_dark_normal = 0x7f0800a2;
        public static final int common_google_signin_btn_icon_dark_normal_background = 0x7f0800a3;
        public static final int common_google_signin_btn_icon_disabled = 0x7f0800a4;
        public static final int common_google_signin_btn_icon_light = 0x7f0800a5;
        public static final int common_google_signin_btn_icon_light_focused = 0x7f0800a6;
        public static final int common_google_signin_btn_icon_light_normal = 0x7f0800a7;
        public static final int common_google_signin_btn_icon_light_normal_background = 0x7f0800a8;
        public static final int common_google_signin_btn_text_dark = 0x7f0800a9;
        public static final int common_google_signin_btn_text_dark_focused = 0x7f0800aa;
        public static final int common_google_signin_btn_text_dark_normal = 0x7f0800ab;
        public static final int common_google_signin_btn_text_dark_normal_background = 0x7f0800ac;
        public static final int common_google_signin_btn_text_disabled = 0x7f0800ad;
        public static final int common_google_signin_btn_text_light = 0x7f0800ae;
        public static final int common_google_signin_btn_text_light_focused = 0x7f0800af;
        public static final int common_google_signin_btn_text_light_normal = 0x7f0800b0;
        public static final int common_google_signin_btn_text_light_normal_background = 0x7f0800b1;
        public static final int googleg_disabled_color_18 = 0x7f0800cf;
        public static final int googleg_standard_color_18 = 0x7f0800d0;
    }
    public static final class id {
        private id() {}

        public static final int adjust_height = 0x7f0a0058;
        public static final int adjust_width = 0x7f0a0059;
        public static final int auto = 0x7f0a0061;
        public static final int dark = 0x7f0a00c9;
        public static final int icon_only = 0x7f0a011d;
        public static final int light = 0x7f0a0137;
        public static final int none = 0x7f0a0186;
        public static final int standard = 0x7f0a0200;
        public static final int wide = 0x7f0a024e;
    }
    public static final class string {
        private string() {}

        public static final int common_google_play_services_enable_button = 0x7f120042;
        public static final int common_google_play_services_enable_text = 0x7f120043;
        public static final int common_google_play_services_enable_title = 0x7f120044;
        public static final int common_google_play_services_install_button = 0x7f120045;
        public static final int common_google_play_services_install_text = 0x7f120046;
        public static final int common_google_play_services_install_title = 0x7f120047;
        public static final int common_google_play_services_notification_channel_name = 0x7f120048;
        public static final int common_google_play_services_notification_ticker = 0x7f120049;
        public static final int common_google_play_services_unsupported_text = 0x7f12004b;
        public static final int common_google_play_services_update_button = 0x7f12004c;
        public static final int common_google_play_services_update_text = 0x7f12004d;
        public static final int common_google_play_services_update_title = 0x7f12004e;
        public static final int common_google_play_services_updating_text = 0x7f12004f;
        public static final int common_google_play_services_wear_update_text = 0x7f120050;
        public static final int common_open_on_phone = 0x7f120051;
        public static final int common_signin_button_text = 0x7f120052;
        public static final int common_signin_button_text_long = 0x7f120053;
    }
    public static final class styleable {
        private styleable() {}

        public static final int[] LoadingImageView = { 0x7f0400a5, 0x7f04016d, 0x7f04016e };
        public static final int LoadingImageView_circleCrop = 0;
        public static final int LoadingImageView_imageAspectRatio = 1;
        public static final int LoadingImageView_imageAspectRatioAdjust = 2;
        public static final int[] SignInButton = { 0x7f040073, 0x7f0400c4, 0x7f040253 };
        public static final int SignInButton_buttonSize = 0;
        public static final int SignInButton_colorScheme = 1;
        public static final int SignInButton_scopeUris = 2;
    }
}
