/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package com.craftman.cardform;

public final class R {
    private R() {}

    public static final class animator {
        private animator() {}

        public static final int card_flip_left_in = 0x7f020000;
        public static final int card_flip_right_in = 0x7f020001;
    }
    public static final class color {
        private color() {}

        public static final int btn_color = 0x7f060038;
        public static final int text_color = 0x7f0600eb;
    }
    public static final class dimen {
        private dimen() {}

        public static final int padding_horizontal = 0x7f07016a;
    }
    public static final class drawable {
        private drawable() {}

        public static final int background_edit_btn = 0x7f080073;
        public static final int background_pay_btn = 0x7f080074;
        public static final int card_gradient = 0x7f08009c;
        public static final int slash_slash_gradiet = 0x7f080126;
    }
    public static final class id {
        private id() {}

        public static final int btn_pay = 0x7f0a007e;
        public static final int card_name = 0x7f0a0091;
        public static final int card_number = 0x7f0a0092;
        public static final int card_preview_back = 0x7f0a0094;
        public static final int card_preview_cvc = 0x7f0a0095;
        public static final int card_preview_expiry = 0x7f0a0096;
        public static final int card_preview_front = 0x7f0a0097;
        public static final int card_preview_name = 0x7f0a0098;
        public static final int card_preview_number = 0x7f0a0099;
        public static final int card_preview_type = 0x7f0a009a;
        public static final int cvc = 0x7f0a00c7;
        public static final int expiry_date = 0x7f0a00f3;
        public static final int expiry_date_layout = 0x7f0a00f4;
        public static final int hide_cvc = 0x7f0a0115;
        public static final int payment_amount = 0x7f0a019f;
        public static final int payment_amount_holder = 0x7f0a01a0;
        public static final int payment_amount_layout = 0x7f0a01a1;
    }
    public static final class integer {
        private integer() {}

        public static final int card_flip_time_full = 0x7f0b0005;
        public static final int card_flip_time_half = 0x7f0b0006;
    }
    public static final class layout {
        private layout() {}

        public static final int cardformlayout = 0x7f0d0050;
    }
    public static final class string {
        private string() {}

        public static final int app_name = 0x7f12001b;
    }
}
